import flet as ft

# _____Couleurs de thème_____
BASE_COLOR = ft.Colors.DEEP_PURPLE
SECOND_COLOR = ft.Colors.DEEP_PURPLE_50
ACCENT_PLUS_COLOR = ft.Colors.DEEP_PURPLE_500
PAGE_BG_COLOR = ft.Colors.DEEP_PURPLE_50
THUMB_COLOR = ft.Colors.DEEP_PURPLE_100
MAIN_COLOR = '#f0f0f6'
EMERALD_GREEN = ACCENT_PLUS_COLOR
